### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by faisalmjanjua** [shekharramola/react-wheel-of-prizes#1]
Getting this error 

`Attempted import error: 'react-wheel-of-prizes' does not contain a default export (imported as 'WheelComponent')`

**Comment by shekharramola** [comment]
@faisalmjanjua , fixed.. please check in the latest version.

**Comment by faisalmjanjua** [comment]
> @faisalmjanjua , fixed.. please check in the latest version.

Thanks, 👍
