### ISSUE TITLE
value.substr is not a function

### ISSUE THREAD

**Issue by mmdzov** [shekharramola/react-wheel-of-prizes#13]
what is this ?

**Comment by mmdzov** [comment]
The above error occurred in the <WheelComponent> component: 

:))

**Comment by mmdzov** [comment]
`
  102 |     );
  103 |   }
  104 | }
> 105 | 
  106 | FlickityComponent.propTypes = {
  107 |   children: PropTypes.array,
  108 |   className: PropTypes.string,
`

`
wheelInit
C:/Users/***/****/****/src/index.js:39
  36 |   options: { draggable, initialIndex },
  37 |   reloadOnUpdate,
  38 |   disableImagesLoaded,
> 39 | } = this.props;
     | ^  40 | const { flickityReady } = this.state;
  41 | if (reloadOnUpdate || (!prevState.flickityReady && flickityReady)) {
  42 |   const isActive = this.flkty.isActive;
`

**Comment by shekharramola** [comment]
I can't see it. can you reproduce the situation at code sandbox?

**Comment by DanielHammerin** [comment]
I also get this error. It worked like a month or two ago.
@mmdzov Did you solve this issue?
