### ISSUE TITLE
How to spin wheel one more time ?

### ISSUE THREAD

**Issue by subnetsRU** [shekharramola/react-wheel-of-prizes#2]
First of all, thanks for your work.

I cant understand how to spin wheel one more time with different _winningSegment_. It`s seems that in render once and thats all. Second click on 'spin' do nothing. How to pass new _winningSegment_ value ... unknown.

Can you help ?

**Comment by shekharramola** [comment]
@subnetsRU , if you want to run it more than once, you can get the latest version and pass `isOnlyOnce={false}`

**Comment by isherwood** [comment]
In v1.0.6 this doesn't seem to be working. I have the component loaded by itself in a fresh CRA app and it needs a page refresh to spin again. 

Thanks for publishing!

**Comment by shekharramola** [comment]
@isherwood , thanks for pointing. Can you please check v1.0.8 ?

**Comment by isherwood** [comment]
Seems to be all good now. Thanks!
