### ISSUE TITLE
Dynamic Segments not working in WheelComponent

### ISSUE THREAD

**Issue by sonykashyap** [shekharramola/react-wheel-of-prizes#23]
Hi,
I have one issue with the wheel. If the static array is being passed to WheelComponent it works fine but if I get the values from inputs and store those values in the array and pass it to WheelComponent it doesn't update.
Could you please help to solve this?

**Comment by shekharramola** [comment]
Hi, can you reproduce the issue into sandbox?

**Comment by sonykashyap** [comment]
> Hi, can you reproduce the issue into sandbox?

Yes, will surely reproduce this.

**Comment by sonykashyap** [comment]
Hi,
Here is the sandbox link.

https://codesandbox.io/s/jm148?file=/src/App.js

**Comment by shekharramola** [comment]
the link which you pasted above does not have any state update. it is just reading segments from the constant variable

**Comment by sonykashyap** [comment]
Add Segment button invokes the "addSegmentHandler" method that updates the state.
You can check the console, state changes, and segments added but the wheel does not update. 

![image](https://user-images.githubusercontent.com/58991617/195582517-aa419ec6-a903-4509-b044-7f7da6a626c5.png)

**Comment by shekharramola** [comment]
Yes I can check that but for that you need to provide code sandbox link

**Comment by shekharramola** [comment]
@sonykashyap you need to provide unique key to the component if you are changing the segments on run time. 

https://codesandbox.io/s/react-wheel-of-prizes-forked-u6vovb?file=/src/App.js

also to learn more about key, you can go through this article

https://epicreact.dev/why-react-needs-a-key-prop/
