### ISSUE TITLE
plaz solve this 

### ISSUE THREAD

**Issue by technothakur1987** [shekharramola/react-wheel-of-prizes#40]
i installed a react with vite app and tried to install npm i react-wheel-of-prizes and i got this errors , i think why this libraray is not compatible with react 18 and its dependies 

'Log files:
C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-04-09T19_36_42_347Z-debug-0.log

# npm resolution error report

While resolving: spinner@0.0.0
Found: react@18.2.0
node_modules/react
  react@"^18.2.0" from the root project

Could not resolve dependency:
peer react@"^16.0.0" from react-wheel-of-prizes@1.1.0
node_modules/react-wheel-of-prizes
  react-wheel-of-prizes@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

i AM A BEGINNER

**Comment by mesuhailpm** [comment]
retry
this command with --force or --legacy-peer-deps at end
