### ISSUE TITLE
What if I want to specify number of seconds the wheel should spin?

### ISSUE THREAD

**Issue by faisalur-rehman** [shekharramola/react-wheel-of-prizes#5]
I want the wheel to spin for 'x' seconds but I don't know how to do it.

**Comment by isherwood** [comment]
This doesn't appear to be built into the component, but it would be a great feature. The duration is too long for a group game. 

How about a pull request?

**Comment by shekharramola** [comment]
@faisalur-rehman  Yes, @isherwood is right. It's not supported yet but a good feature to have. I will start working on it and if anyone wanted to contribute, you are very welcome!

**Comment by shekharramola** [comment]
@faisalur-rehman , you can play with `upDuration` and `downDuration` and match with your need in the latest version. I have updated readme

**Comment by faisalur-rehman** [comment]
Thanks. I will surely check it.

**Comment by isherwood** [comment]
Checked and approved. Nice! I also appreciate the sizing. I was planning on implementing that myself for my project.
